[package]
name = "hidden-number"
version = "1.0.0"
authors = ["LightDiscord <arnaud@lightdiscord.me>"]
publish = true
readme = "README.md"
repository = "https://github.com/LightDiscord/hidden-number.rs"

[dependencies]
